### ISSUE TITLE
Conveying NAT firewall port re-writing to mosh

### ISSUE THREAD

**Issue by earlchew** [keithw/mosh#494]
I am using a firewall which re-writes TCP/UDP port numbers.

I'm considering a patch to bin/mosh to accommodate this, and I'm soliciting advice on a reasonable approach.

Suppose the firewall will rewrite port numbers from 40001 to 50001 (as an example). This means that I want to issue -p 50001 to instruct the server to listen on 50001, but I also want the client to send to port 40001 (which the firewall will rewrite).

I'm thinking:
```
mosh -p 40001/50001
mosh -p 40001/50001:50099
```
would be a reasonable way to indicate this.

The second example shows how it could be combined with a server side port range. Suppose the server responded with port 50055, the client would use:
```
40001 + (50055 - 50001) = 40055
```

**Comment by cgull** [comment]
Duplicates #497.
