### ISSUE TITLE
Mouse support does not work 100%

### ISSUE THREAD

**Issue by creack** [keithw/mosh#505]
#461 is awesome! It enabled the mouse support.

However, this doesn't work at 100%. Emacs has difficulities catching the mouse (I have to disable/reenable the xterm-mouse-mode) and when I try to select something it tells me `Unexpected sequence from XTerm`. It works fine on SSH.

The selection works fine on tmux though.

```
$> emacs --version
emacsclient 24.3
```

**Comment by dbkaplun** [comment]
:+1:

**Comment by cgull** [comment]
I *think* this is fixed by #569 and/or #576.  In any case, the code has changed, and any issues should be reported anew.
