### ISSUE TITLE
vim syntax highlighting fails inside tmux

### ISSUE THREAD

**Issue by berceanu** [keithw/mosh#557]
Steps reproduce:
connect to another machine using mosh
launch a tmux session
open a code file in vim
Result: syntax highlighting is almost completely lost
The same steps with ssh instead of mosh do not change the vim colors in any way.
mosh screenshot:
![mosh](https://cloud.githubusercontent.com/assets/4405658/4516373/b9966f6c-4bf2-11e4-9196-eb9bbad051a3.png)
ssh screenshot:
![ssh](https://cloud.githubusercontent.com/assets/4405658/4516375/c1be8cc4-4bf2-11e4-8058-e467b32d8c23.png)

**Comment by cgull** [comment]
No response from original reporter.  See also #507.
