### ISSUE TITLE
Mouse reporting stops on window resize

### ISSUE THREAD

**Issue by wlcx** [keithw/mosh#560]
With a mosh session in iTerm2 on OSX and tmux, mouse reporting works and the cursor is displayed with a circle on the bar. Resizing the window in any direction stops mouse reporting from working, with the cursor changing to a non-circled state. Using ssh, mouse reporting stays active on window resize.

**Comment by cgull** [comment]
I think this is resolved by #576, it tests out OK for me.  See that issue for a possible explanation of what causes it.
