### ISSUE TITLE
Mouse mode gets triggered with "Shift + Mouse" in mosh + tmux (but not ssh)

### ISSUE THREAD

**Issue by blueyed** [keithw/mosh#566]
Usually pressing Shift while using the (pressed) mouse this gets bypassed by urxvt, and will only extend/set the X selection, but is not forwarded to the terminal.

When using mosh + tmux, this does not work - but it does with ssh + tmux.

Using `set -q mouse-mode copy-mode` (instead of `on`) in tmux works around this.

TEST CASE:
1. `mosh localhost -- tmux -f /dev/null`
2. Enable mode-mouse: <kbd>C-b</kbd> `:set mode-mouse on` <kbd>CR</kbd>
3. Press Shift and select something with the mouse

While the X selection gets set, tmux also enters copy-mode (see the upper right).

I am using mosh and urxvt from Git, and tmux 1.9.

**Comment by cgull** [comment]
One way or another, we think this is resolved, in #569 or in #576.
