### ISSUE TITLE
Using ProxyCommand breaks ssh_known_hosts when using CanonicalizeHostname

### ISSUE THREAD

**Issue by tomprince** [keithw/mosh#577]
When ssh's `CanonicalizeHostname` option is set to `yes`, ssh will fail to find the proper host key when it canonicalizes a name.
```
local% mosh -- remote
The authenticity of host 'remote (<no hostip for proxy command>)' can't be established.
```
vs.
```
local% ssh -Snone remote
Last login: Tue Dec 30 01:26:05 2014 from remote.example.com
remote%
```

ssh_config:
```
CanonicalDomains example.com
CanonicalizeHostname yes
```
I have a `remote.example.com` host key entry, but not a `remote` host key.

**Comment by andersk** [comment]
Use `CanonicalizeHostname always` to tell SSH to perform canonicalization even for proxied connections.

Alternatively, make the alias this way instead of relying on canonicalization:
```
Host remote
    HostName remote.example.com
```

**Comment by tomprince** [comment]
I (reasonably) don't want canonicalization for proxied connections.

**Comment by andersk** [comment]
For clarity: Mosh doesn’t support proxied connections (and can’t, without doing something tricky in the way of UDP tunneling or NAT/firewall hole punching). It uses `ProxyCommand` with a trivial wrapper just so it can get the remote IP address.

I’m not sure I understand the use case for having `ssh` canonicalize names for non-proxied connections only. But if that’s what you want `ssh` to do, you could locally alias `mosh` to `mosh --ssh='ssh -o CanonicalizeHostname=always`, or you can use the alternative I mentioned above that doesn’t rely on canonicalization.

**Comment by tomprince** [comment]
This isn't something that I, as a user of mosh, should have to think about.
