### ISSUE TITLE
mosh can't show "\u2699"

### ISSUE THREAD

**Issue by timfeirg** [keithw/mosh#582]
The character "\u2699" looks like this: ⚙, a symbol used to indicate the existence of a background job in my favourite zsh theme [agnoster](https://gist.github.com/agnoster/3712874), which in local terminal, should looks like this:

![timfeirg_timfeirg-mba____workspace-setup_and_new_issue_ _keithw_mosh](https://cloud.githubusercontent.com/assets/4319104/6043981/46b3b920-accb-11e4-9565-1eadec8aa28a.png)

```bash
$ echo "\u2699"
```

And nothing shows up at mosh terminal.

**Comment by keithw** [comment]
Mosh is just using your system's libc (and the current locale) to determine whether a character is printable or not. GNU libc has this character, but OS X does not have as recent a version of Unicode. You can check with this program: http://web.mit.edu/keithw/Public/wcwidthtest.c

See also https://github.com/keithw/mosh/issues/478

We have some general plans to fix this in the future by shipping our own Unicode tables (or deriving them from the client's terminal), but for now your best bet may be to file a radar bug with Apple and ask them to update.
