### ISSUE TITLE
mosh OS X installer doesn't work on OS X 10.9

### ISSUE THREAD

**Issue by bgertzfield** [keithw/mosh#586]
When installing the mosh OS X .pkg from https://mosh.mit.edu/mosh-1.2.4-3.pkg on OS X 10.9.5, I get the error:

    Unapproved caller.
  
    SecurityAgent may only be invoked by Apple software.

I see this in system.log:

    Feb 25 09:48:59 beng-mbp SecurityAgent[99739]: Failed to create agent mechanism, failing authentication!

Install log: http://pastebin.com/vHEhSbc2

![screen shot 2015-02-25 at 9 49 02 am](https://cloud.githubusercontent.com/assets/671827/6376622/ec498852-bcd3-11e4-906b-980abc293b3c.png)

**Comment by keithw** [comment]
Thanks for the report -- we may have to deprecate the Mac pkg unless somebody knows of how we are supposed to build installers on OS X 10.9. @eminence, do you have any ideas?

**Comment by bgertzfield** [comment]
It turns out this is a known OS X 10.9 bug. Renaming /var/folders to
another location and rebooting the machine worked around the issue.
2015年2月25日(水)、10:02 Keith Winstein <notifications@github.com>:

**Comment by bgertzfield** [comment]
Yep, confirmed the workaround (renaming `/var/folders` and rebooting) works. Sorry for the noise.
