### ISSUE TITLE
Add option to mosh-server to use preconfigured key

### ISSUE THREAD

**Issue by on247** [keithw/mosh#590]
A option that allows mosh-server to use a predefined-key stored somewhere in the filesystem
Like:
mosh new -k /home/someone/mosh.key ...

This would allow mosh to work without using SSH for devices which dont have any way of being acessed without mosh to get the key from

**Comment by andersk** [comment]
Mosh must generate a new random key for every session because it’s not cryptographically secure to encrypt different messages with the same key and nonce. If you have a device that cannot be accessed and you want to add a way of accessing it using a preconfigured key, that way is SSH.
