### ISSUE TITLE
Support for hmac-sha2-*-etm@openssh.com

### ISSUE THREAD

**Issue by pysiak** [keithw/mosh#591]
When connecting to a server configured as per moden crypto standards (such as Bettercrypto.org or those shown here: https://stribika.github.io/2015/01/04/secure-secure-shell.html) I'm ending up with lack of support for those MACs, see below:

```
Could not connect via ssh: kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com], client [hmac-sha1]

SSH Login failed.

Mosh has exited.
Press "x" to close the window.
```

Is support for this possible in mosh?

**Comment by andersk** [comment]
This is an ssh issue, not a mosh issue. From your `Press "x" to close the window` message, it sounds like you’re using mosh-chrome (which is based on this project, but is not this project), in which case there’s a report of this at rpwoodbu/mosh-chrome#75.

**Comment by pysiak** [comment]
Aah, sorry! and Thanks!
