### ISSUE TITLE
Mosh usage with ssh config not working and/or unclear

### ISSUE THREAD

**Issue by NoUsername** [keithw/mosh#592]
Tried using mosh today, had a few issues getting it to work at first (e.g. had to set LC_ALL, ... documentation and/or error messages could be a little bit more helpful/clear on this but it's fine).

My biggest issue was that at first i thought mosh would use (read) `.ssh/config` so i tried to run sth like: `mosh myServer` where `myServer` exists in my  `.ssh/config`.
I then saw in the Mosh FAQ that you can use `--ssh`. However here my issue is that i have to specify a hostname additionally, so i cannot simply run `mosh --ssh="ssh myServer"` but i have to run `mosh myServer.com --ssh="ssh myServer"` which seems a little repetitive.

At least I thought that this would/should work, however when i run this i get:

```
bash: myServer.com: command not found
Connection to myServer.com closed.
/usr/bin/mosh: Did not find mosh server startup message.
```

So it seems for some reason the hostname i pass to mosh gets executed in the remote shell as a command (which obviously fails)?
I don't understand why this happens or how I could fix it.
The only working way I found so far is this: `mosh myServer.com --ssh"ssh -p 1234"`
Which isn't what I want to run because I don't want to remember/duplicate the port which is configured in my `.ssh/config` file.

**Comment by andersk** [comment]
If you run `mosh myServer`, where `myServer` exists in `~/.ssh/config`, then those `~/.ssh/config` settings will be used. Note SSH (and therefore Mosh) does not treat `myServer` as the same as `myServer.com`, _even if those names happen to resolve to the same machine_; the hostname strings must be textually equal.

If you specify `--ssh`, you must not include the hostname within the argument to `--ssh`; the hostname is passed to SSH automatically.

**Comment by NoUsername** [comment]
You are right! My apologies. I guess it just didn't work for me at first because of the other issues I had and it seems I didn't try that again after I had resolved those.

Thank you for this great project!
