### ISSUE TITLE
update answer to "Q: Why is my terminal's scrollback buffer incomplete?" FAQ

### ISSUE THREAD

**Issue by requiredfield** [keithw/mosh#594]
The answer to this question on https://mosh.mit.edu/#faq refers readers to #2 and other issues linked from there (e.g. #122). Those issues have long-running threads over several years, haven't been updated recently, and, most important, are closed despite the issue still being present, so users looking for the current status of your progress may find this FAQ leads to more questions than answers. Can you please update the FAQ with a more easily accessible way we can follow along?

Submitted with <3 for mosh. Thanks for your consideration and for the great software. mosh rocks.

**Comment by andersk** [comment]
We don’t have anything concrete to update it with, but if you have an idea (or a pull request), it should go to the separate project https://github.com/keithw/moshweb.

**Comment by requiredfield** [comment]
sorry for reporting in the wrong place. migrated to keithw/moshweb#29.
