### ISSUE TITLE
update to chromebook breaks tab completion

### ISSUE THREAD

**Issue by sasnfbi1234** [keithw/mosh#598]
after updating my chromebook to Version 43.0.2357.32 beta tab completion has stopped working in the mosh chrome app. it worked before the update and does not work at all now.

**Comment by andersk** [comment]
The Mosh Chrome app is developed [elsewhere](https://github.com/rpwoodbu/mosh-chrome). It looks like your issue has already been reported at rpwoodbu/mosh-chrome#88.
