### ISSUE TITLE
Official Ubuntu PPA lacks vivid support

### ISSUE THREAD

**Issue by neopostmodern** [keithw/mosh#604]
The (recommended) Ubuntu PPA lacks support for the last release (15.04 / `vivid`):

```plain
W: Failed to fetch http://ppa.launchpad.net/keithw/mosh/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/keithw/mosh/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found
```

I double-checked that it's not my internet connection: http://ppa.launchpad.net/keithw/mosh/ubuntu/dists/ - `vivid` isn't listed.

It would be great to get support for `vivid` too :)

**Comment by keithw** [comment]
Thanks, builds fired off.

In the meantime, you can just install "mosh" from the Ubuntu universe (no PPA necessary) -- the versions are the same.
