### ISSUE TITLE
Suspend and "export"  mosh sessions

### ISSUE THREAD

**Issue by phmarek** [keithw/mosh#608]
Let's say I have an active mosh session on one machine, and want to "move" it to another one.

If mosh would allow to export its internal cryptographic state (and network addresse) into a single base64 blob and to re-use that when starting up again it would be easily possible to eg. move an active, authenticated session to the smartphone (eg. via copy/paste of that "secret").

In other words: this would be a "cold-state" suspend-to-disk equivalent to the available Ctrl-^ Ctrl-Z suspend functionality.

My take on the security implications is if you have access to the mosh process, you can `gdb` it anyway and discover all needed details - so I don't think this presents any additional risks.

**Comment by cgull** [comment]
This more or less duplicates #394; the best solution currently is screen or tmux.

**Comment by phmarek** [comment]
Sorry, no, that's not a duplicate.
This issue is about *exporting* the state, so that another device can take over the active connection.

Yes, #394 is similar, but not the same.

**Comment by cgull** [comment]
Well, I see this as a slight superset of that, the extra bit being managing/locking clients from multiple machines attempting to access the same session, and the discussion in #394 touches on that. Keep in mind that for Mosh, the state is more or less the same on both client and server and could be exported by either side.  But perhaps I'm misreading?

**Comment by phmarek** [comment]
Well, AFAICT the server can't know (and currently won't get told and won't remember) the outside-visible address that the client accessed (which might be different because of DNAT). But yes, of course it could create a new crypto state.

I think as soon as the *server* side does the the next requested feature is to have multiple clients connect to one server, because it's just another small step... IMO telling the client to "suspend to disk" via some keyboard combination and then starting it again makes it more clear that server:client is a 1:1 correspondence. The user ("client") could be assured that she's the only one, and there's not someone else piggybacked on the same mosh server instance.

**Comment by cgull** [comment]
Aside from the question of "what is Mosh's security model, and what new features are acceptable?"...

Well, I had envisioned the server continuing to use the same crypto state.  You have a good point about not having full knowledge of client state at the server end, though.

Some thoughts I've had about this issue:

* If you adopt a security model where you trust all your clients all the time (and I think you must in any case), then the clients can cooperate and each send their own unique identifier with each packet.  The server tracks which identifier it's currently using, and when a new identifier appears, it can choose which to use-- continue with the old one or switch to the new one.  
* A better name of the action involved might be "attach/detach", like screen and tmux-- the difference here is that you can have only one client active at any time, and that you get a very-confidential blob of session state to convey from the detached client to the newly attaching one.  You'd have the detach action attached to some new escape sequence, say `ctrl-^ d`, and the user would have to consciously invoke it.  If the blob's small enough, the detaching client could print it to console on the way out, and it would never be data at rest on the mosh-client machine.  The user could cut/paste it to their new mosh client, wherever it is.  (Of course, putting this info on your environment's clipboard has...issues.  mosh-agent, anyone?)

I'm not keen on the idea of having a single session's server allow multiple clients.  I think it's a *lot* more than just another small step to do that, and screen/tmux/others do a way better job than mosh could hope to achieve with its current popularity.

**Comment by andersk** [comment]
This feature request scares me from a cryptographic perspective. The mosh-client internal state includes a cryptographic nonce that must never be reused, and I worry that if you allow the state to be serialized, it would be hard to stop users from unknowingly compromising their own security. We could solve this by adding a way to negotiate a new session key for each resume, but that means protocol changes and extra security-critical complexity.

Also, from a terminal perspective, the existing C-^ C-z support is incomplete (e.g. #505), and such problems would be compounded if mosh-client was allowed to resume on a different terminal.

**Comment by cgull** [comment]
@phmarek, what is your use case here?  What does having a movable client session state get you that you can't have with independent mosh sessions and screen/tmux on the server?  I'm not seeing the value in this proposal.

**Comment by phmarek** [comment]
@cgull, it's exactly your second point above. Single client at any time, but allowing to "move" to another device.
While I don't have a problem using the clipboard for that, I agree with @andersk that negotiation of a new key might be a good idea. In this case, the issue becomes generating/exporting/passing a shared key (from which all other values can be derived); I guess that 32 bytes == 256 bit == 52 base64 characters (plus server IP and port) should be small enough for copy/paste. If it gets smaller, even typing would be possible (if ''0OiI1'' are not all used, perhaps ;)

My final use case is having a statically compiled mosh-client on my smartphone, that gets its crypto-state from some other device. Eg. ''mosh <server>'' on the notebook, then export the session, and re-start it on the smartphone in a terminal.
This way I can avoid to have quite a few things on the phone: a) the SSH Key b) a perl binary c) all the various libraries.

**Comment by eminence** [comment]
I'm still a little confused about how this would work in practice.  Assuming you had the most flexible implementation of the feature, what does the work flow look like.  Let's start by assuming that you are sitting in front of your desktop in your home, and have run "mosh user@remote.server.com".  At some point you get up from your desktop and want to continue the session on your mobile phone.   So you issue a command to mosh-server, which causes it to write some state to disk, and the you close mosh-client.  How do you get that state on remote.server.com over to your mobile phone?  Maybe you ssh from phone to remote.server.com, and copy it over via scp?   Or a system clipboard on your phone?

**Comment by cgull** [comment]
Now that @andersk has explained his worries, I'm scared too, because I can easily construct a foot-shooting scenario that doesn't even need any help from your friendly local nation-state surveillance agency:
* user detaches original mosh client, gets session state, copies it
* user tries to attach with new mosh client, pastes state, startup fails for whatever reason (probably network connectivity), but in a way that has traffic observable by an adversary.
* user goes "Huh...that didn't work", repeats on his other phone.  **Oops**.

The Perl argument doesn't hold much water, since it's already been rewritten at least twice in C/C++, and in this scenario you might just as well use mosh-client directly anyway.

And it seems to me that there's a workable already-secure and already-available solution to this problem:  Use screen/tmux.  On your existing mosh session, start a new mosh-server.  Convey the key/IP/port you get from this server to the new device, the same way you'd have copied the entire session state.

**Comment by phmarek** [comment]
Well, my workflow was described by @cgull in the meantime.

I didn't know that ''mosh-server'' and ''mosh-client'' are that easy to combine... Well, the command line help ''Usage: mosh-client IP PORT'' could mention the ''MOSH_KEY'' environment variable, too, but otherwise that looks more or less like what I want, thanks a lot!

Now all I need is a static build of mosh-client, and some patch to make it suspend/resume as per android standards (to keep memory usage low).
