### ISSUE TITLE
unicode emojis not rendered

### ISSUE THREAD

**Issue by fuzzy76** [keithw/mosh#612]
unicode emojis like 😀 does not render. SSH handles them fine.

**Comment by cgull** [comment]
This is almost certainly a duplicate of #361-- but if you think it's not, can you give some more detail?
* What unicode character fails?
* What local terminal emulator are you using, on what OS/version?
* What OS/version are mosh-client and mosh-server running on?
* What app/OS/version is generating the Unicode characters?

**Comment by cgull** [comment]
Oh never mind, I see the IRC scrollback now.

**Comment by fuzzy76** [comment]
That was not me, but ok. That too. :)

- All unicode emojies / smileys like the 😀 or 🐻
- From the builtin terminal.app on OS X using mosh 1.2.4
- To Debian Jessie using mosh 1.2.4a
- A simple echo "😀";  in a bash script.

If I log in using SSH and run the script, the emoji outputs fine.
If I log in using mosh and run the script, the output is blank.

**Comment by cgull** [comment]
Yes, this is a duplicate of #361.  Both OS X libc and GNU libc have Unicode implementations too old to know about emoji.

**Comment by fuzzy76** [comment]
In that case, let's close this. :)
