### ISSUE TITLE
Rename of scripts/mosh to scripts/mosh.pl breaks Homebrew formula

### ISSUE THREAD

**Issue by schmatz** [keithw/mosh#614]
Is renaming that file necessary? If so, I'll go open a PR on the Homebrew formula. If not, I'll open a PR renaming it back.

**Comment by cgull** [comment]
It's a generated file now.  I assume the formula is editing it before the build when it doesn't exist yet.  I'll look at it more tonight, and maybe fix it.

**Comment by schmatz** [comment]
You're right, it edits it. Thanks!

**Comment by cgull** [comment]
Addressed in homebrew/homebrew#40338.

**Comment by cgull** [comment]
Upstream accepted the pull request, this should be fixed now. `brew update`
