### ISSUE TITLE
Enable altivec on ppc64el

### ISSUE THREAD

**Issue by leitao** [keithw/mosh#615]
mosh currently doesn't build on new IBM POWER architecture ABI v2 with altivec enabled. In order to build it, we need to disable altivec, using the following patch:

-#elif __ALTIVEC__
+#elif __ALTIVEC__ && _CALL_ELF != 2

So, we want to enable altivec optimization on ABI v2 again.

**Comment by cgull** [comment]
Could you do a pull request on Github, please?

**Comment by cgull** [comment]
So a little digging around reveals that you're probably trying to get this code to run on Linux PPC/64, little-endian, with a new ABI.  They all come together, apparently, but which of these three issues is breaking the compile?  Is _CALL_ELF the right test?

Also, have you tried this on all compilers available in this environment (I *think* that's gcc, clang, IBM)?

**Comment by edelsohn** [comment]
The Altivec code currently is big-endian.  It needs to be adjusted for little-endian.  _CALL_ELF is the correct macro to distinguish between the the big-endian ABI and the little-endian ABI.  Eventually a version of Altivec support for LE needs to be contributed.

**Comment by keithw** [comment]
This is still breaking the build on ppc64el. https://buildd.debian.org/status/fetch.php?pkg=mosh&arch=ppc64el&ver=1.2.4.95rc1-1&stamp=1433921864

We should probably take Ubuntu's patch: http://launchpadlibrarian.net/171225681/mosh_1.2.4a-1build1_1.2.4a-1ubuntu1.diff.gz

(also suggested above and at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743019)

**Comment by cgull** [comment]
A patch, that's authored, (semi)-documented, and tested?  Yes, let's take it.  My one concern is that the Debian build log doesn't show the actual error, and the fail seems to be in `make test`, not the main build, as I'd expect.

**Comment by cgull** [comment]
My concern is misplaced: this is an endianness fail, and `make check` is the expected place for it to fail.
