### ISSUE TITLE
New release, please!

### ISSUE THREAD

**Issue by dbkaplun** [keithw/mosh#616]
It's been two years. I think it's time for a new release, don't you? :+1:

**Comment by glensc** [comment]
if you look at [recent commits](https://github.com/keithw/mosh/commits/master), you would see that @cgull is working hard recently resolving loads of issues/pull-requests. i think it's coming soon!

**Comment by cgull** [comment]
Yes, I'm working on a 1.2.5 now. It's intended as a stable release of what's in Git now, no new features.  I think I've dealt with the most difficult issues for 1.2.5, and we should have a release candidate in a few days.  After that, I want to do a release with straightforward enhancements.

I announced this in email, I should probably add issues and tags here for this.

**Comment by xtaran** [comment]
While "1.2.5" is a perfect version number for a bugfix-only release, I think the next release with enhancements shouldn't be dubbed just "1.2.6" as suggested in another thread. New features should have at least an "1.3" if not a "2", at least if you adhere to Semantic Versioning.

See http://semver.org/ for details about Semantic Versioning.
