### ISSUE TITLE
mosh+weechat+mouse scrolling = broken

### ISSUE THREAD

**Issue by dbkaplun** [keithw/mosh#617]

**Comment by cgull** [comment]
What terminal are y ou using?  This worked fine for me in testing.  Also, how wide is the terminal, and are you trying to scroll the messages buffer or the user list?

**Comment by dbkaplun** [comment]
iTerm2 2.1.1, size 24x80, trying to scroll the messages buffer.

**Comment by cgull** [comment]
Also, what's the behavior you're seeing?

My Mac is at home, so I can't test iTerm right now. This works for me with XTerm.

**Comment by dbkaplun** [comment]
It scrolls the terminal scrollback itself, making weechat disappear below.

**Comment by cgull** [comment]
That suggests XTerm mouse mode isn't getting set at all.  Are you sure mouse mode is enabled both in iTerm2 and weechat?

**Comment by cgull** [comment]
And that you're using the latest Mosh on both client and server?  I'm not sure what will happen if there is version skew.

**Comment by dbkaplun** [comment]
Works over SSH, fails in mosh. Same version (HEAD).

**Comment by cgull** [comment]
It works fine for me from iTerm2 2.1.1 to an Ubuntu 14.04 system with WeeChat 1.0.1.

You're going to have to give a more useful problem report before we can go any further with this-- versions of everything, in particular.  Is this a regression from an older build?

**Comment by dbkaplun** [comment]
Confirmed!
