### ISSUE TITLE
cant connect to vps

### ISSUE THREAD

**Issue by happyjohn2** [keithw/mosh#638]
mosh-client needs a UTF-8 native locale to run.

Unfortunately, the client's environment ([no charset variables]) specifies
the character set "US-ASCII".

LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

i can mosh my vps with my mac/android but cant use my chromebook(crouton)

**Comment by keithw** [comment]
You will need to be in a UTF-8 locale on your local machine. (Setting LANG locally to en_US.UTF-8 may do this for you.) Alternately, you can use the mosh-chrome tool which runs within Chrome and ChromeOS.
