### ISSUE TITLE
iterm2's deep tmux recognition and mosh

### ISSUE THREAD

**Issue by mprobst** [keithw/mosh#640]
I'm usually running a ssh terminal within iTerm2, and use iTerm2's features to recognize a tmux session and render its UI natively (i.e. Mac OS tabs/windows instead of console tabs/windows). My command line is:

    ssh [host] 'tmux -CC new-session -AD my-session-name'

Admittedly I don't really understand how that works, but it certainly doesn't when using `mosh`.

    mosh [host] 'tmux -CC new-session -AD my-session-name'

* This connects, and then immediately closes the connection again.
* Connecting and running `tmux -CC ...` separately does print out tmux' control commands, but doesn't render them, i.e. iTerm2 doesn't recognize them.
* Just running plain `tmux` works, but doesn't give the deep integration.

**Comment by cgull** [comment]
This, unfortunately, isn't going to work.  Mosh is a virtual terminal emulator (much like tmux, actually), and doesn't pass data unaltered from server to client (it updates/redraws what you see on the screen instead).  So it can't be used as a conduit for tmux in control mode.

**Comment by joeshaw** [comment]
@mprobst you might be interested in following #41 and #120 which both would need a reliable octet stream implementation to be implemented.  tmux's control mode could conceivably also run over this.  Also see https://www.mail-archive.com/mosh-devel@mit.edu/msg00304.html

**Comment by mprobst** [comment]
Thanks for the pointer @joeshaw, subscribed there.

**Comment by prologic** [comment]
@mprobst Are you planning on attempting to work on this ITerm2+mosh+tmux integration? I've subscribed myself to #41 and #120 and read through the mailing list thread; I haven't seen any efforts in this space so far?

**Comment by mprobst** [comment]
Sorry, I'm only a user of iTerm and won't have the cycles (nor expertise
really) to get this done.

James Mills <notifications@github.com> schrieb am Di., 6. Okt. 2015, 22:23:

**Comment by prologic** [comment]
Ahh sorry I did not realize; I'd still like to see what we can do to get this done though! I'm only a user too and I'm sure iTerm2 would require some language skills I probably don't have (ObjC?) :)

**Comment by rbrewer** [comment]
Have you tried the [iTerm 2, tmux, and mosh solution](http://unix.stackexchange.com/a/161906)?

**Comment by mprobst** [comment]
@rbrewer that does not include support for tabs, windows, etc, right?
