### ISSUE TITLE
Ubuntu, mosh and autocomplete

### ISSUE THREAD

**Issue by davidbaumann** [keithw/mosh#645]
Hello,

I am running Ubuntu 15.04 and using the included version of mosh:

    mosh --version
    mosh 1.2.4a

so I have a .ssh/config file, containing some hosts.
When I want to ssh them, I just type

"ssh my<tab>", and it will autocomplete "ssh myhost".

With mosh, this doesn't work.

I don't know wheter it's Ubuntu or mosh related, but hope, it's the right place to discuss about.

    echo $SHELL
    /bin/bash

**Comment by xtaran** [comment]
Please also specify which shell you're using, e.g. bash, zsh, etc.

**Comment by davidbaumann** [comment]
Added the requested information.

**Comment by cgull** [comment]
Fixed in the next release, as they say. See #628.

@davidbaumann, if you install the Ubuntu PPA, I think you'll find that this is fixed.

**Comment by FreedomBen** [comment]
I'm on Fedora 32 and still seeing this issue.  Is there anything special to get it working on Fedora?
